######################## default configuration ####################
baseURL = "http://productosluan.com//"
languageCode = "en-us"
title = "Productos Luan"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Inicio"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Sobre Nosotros"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Nuestros Precios"
URL = "price"
weight = 4

[[menu.main]]
name = "Contactenos"
URL = "footer"
weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Producto Luan"
description = "Productos Luan"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright 2020 - All Rights Reserved. Design and Developed By Themefisher.com"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "<span>CONTACTENOS</span> "
blogTitle = "<span>BLOG POSTS</span>"
galleryTitle = "Nuestros <span>Productos</span>"
socialTitle = "Nuestras <span>redes</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Nuestro Telefono:"
icon = "fa fa-phone"
content = "+506 8952 6500"

[[params.footer.contactItem]]
title="Nuestra Direcci√≥n"
icon = "fa fa-map-marker"
content = "Las Brisas de Zarcero, Costa Rica"


######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/queso-1.png"

[[params.footer.gallery]]
image = "images/slider/queso-2.png"

[[params.footer.gallery]]
image = "images/slider/queso-3.png"

[[params.footer.gallery]]
image = "images/slider/queso-4.png"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/quesosLuanCR"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/productosluancr/"
